services:
  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"

  scheduler:
    build: .
    container_name: scheduler
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      APISERVER_HOST: host.docker.internal
