// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.1
//   protoc               v5.27.2
// source: src/proto/apiserveretcd.proto

/* eslint-disable */
import * as _m0 from "protobufjs/minimal";

export const protobufPackage = "apiserver";

export interface PodRequest {
  name: string;
  containers: ContainerMetadata[];
}

export interface ContainerMetadata {
  name: string;
  image: string;
}

export interface PodResponse {
  message: string;
  podId: string;
}

function createBasePodRequest(): PodRequest {
  return { name: "", containers: [] };
}

export const PodRequest = {
  encode(message: PodRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    for (const v of message.containers) {
      ContainerMetadata.encode(v!, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): PodRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePodRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.containers.push(ContainerMetadata.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PodRequest {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      containers: globalThis.Array.isArray(object?.containers)
        ? object.containers.map((e: any) => ContainerMetadata.fromJSON(e))
        : [],
    };
  },

  toJSON(message: PodRequest): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.containers?.length) {
      obj.containers = message.containers.map((e) => ContainerMetadata.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PodRequest>, I>>(base?: I): PodRequest {
    return PodRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PodRequest>, I>>(object: I): PodRequest {
    const message = createBasePodRequest();
    message.name = object.name ?? "";
    message.containers = object.containers?.map((e) => ContainerMetadata.fromPartial(e)) || [];
    return message;
  },
};

function createBaseContainerMetadata(): ContainerMetadata {
  return { name: "", image: "" };
}

export const ContainerMetadata = {
  encode(message: ContainerMetadata, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.image !== "") {
      writer.uint32(18).string(message.image);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ContainerMetadata {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseContainerMetadata();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.image = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ContainerMetadata {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      image: isSet(object.image) ? globalThis.String(object.image) : "",
    };
  },

  toJSON(message: ContainerMetadata): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.image !== "") {
      obj.image = message.image;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ContainerMetadata>, I>>(base?: I): ContainerMetadata {
    return ContainerMetadata.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ContainerMetadata>, I>>(object: I): ContainerMetadata {
    const message = createBaseContainerMetadata();
    message.name = object.name ?? "";
    message.image = object.image ?? "";
    return message;
  },
};

function createBasePodResponse(): PodResponse {
  return { message: "", podId: "" };
}

export const PodResponse = {
  encode(message: PodResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    if (message.podId !== "") {
      writer.uint32(18).string(message.podId);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): PodResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePodResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.message = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.podId = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PodResponse {
    return {
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      podId: isSet(object.podId) ? globalThis.String(object.podId) : "",
    };
  },

  toJSON(message: PodResponse): unknown {
    const obj: any = {};
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.podId !== "") {
      obj.podId = message.podId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PodResponse>, I>>(base?: I): PodResponse {
    return PodResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PodResponse>, I>>(object: I): PodResponse {
    const message = createBasePodResponse();
    message.message = object.message ?? "";
    message.podId = object.podId ?? "";
    return message;
  },
};

export interface ApiserverEtcdService {
  CreatePod(request: PodRequest): Promise<PodResponse>;
}

export const ApiserverEtcdServiceServiceName = "apiserver.ApiserverEtcdService";
export class ApiserverEtcdServiceClientImpl implements ApiserverEtcdService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || ApiserverEtcdServiceServiceName;
    this.rpc = rpc;
    this.CreatePod = this.CreatePod.bind(this);
  }
  CreatePod(request: PodRequest): Promise<PodResponse> {
    const data = PodRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "CreatePod", data);
    return promise.then((data) => PodResponse.decode(_m0.Reader.create(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
